# Generated by Django 2.0.4 on 2019-11-16 19:58

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
