# Generated by Django 2.0.4 on 2019-11-23 21:50

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.AddField(
            model_name='letter',
            name='image_s3',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='image_s3',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
