# Generated by Django 2.2.5 on 2019-09-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifs',
            old_name='artist',
            new_name='caminho',
        ),
        migrations.RenameField(
            model_name='gifs',
            old_name='title',
            new_name='nome',
        ),
    ]
