# Generated by Django 2.0.4 on 2019-11-16 20:03

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191116_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='images',
        ),
        migrations.RemoveField(
            model_name='word',
            name='images',
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
