# Generated by Django 2.0.4 on 2019-11-16 20:06

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191116_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image_s3',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='image_s3',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(upload_to='letter/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to='word/'),
        ),
    ]
